```{r eval=FALSE}

# conda activate cicero

library(Seurat)
library(tidyverse)
library(RColorBrewer)
library(MetBrewer)
library(viridis)
library(patchwork)
library(cowplot)
library(grid)
library(gridExtra)
library(WGCNA)
library(hdWGCNA)
library(ggrepel)
theme_set(theme_cowplot())

source('/dfs7/swaruplab/smorabit/pipelines/sn-rna-seq/bin/sc_utilities.R')
source('/dfs7/swaruplab/smorabit/analysis/scWGCNA/bin/spatial_functions.R')
source("/pub/smorabit/hdWGCNA/bin/spatial_functions.R")

setwd('/dfs7/swaruplab/smorabit/collab/woodlab/reinstatement_2022')

# output directories
data_dir <- "data/"
fig_dir <- 'figures/'

# load seurat obj
seurat_obj <- readRDS("/dfs7/swaruplab/smorabit/collab/woodlab/reinstatement_2022/data/Reinstatement_2022_seurat.rds")


```

Combine the markers into one table :

```{r eval=FALSE}

##############################################################
# cluster markers
##############################################################

DEG_dir <- "/dfs7/swaruplab/smorabit/collab/woodlab/reinstatement_2022/DEGs/cluster_markers/"
DEG_tests <- dir(DEG_dir)

combined <- Reduce(rbind, lapply(DEG_tests, function(file){
  read.csv(paste0(DEG_dir, '/', file))
}))

write.csv(
  combined,
  file='/dfs7/swaruplab/smorabit/collab/woodlab/reinstatement_2022/DEGs/data/cluster_markers.csv',
  quote=FALSE, row.names=FALSE
)

##############################################################
# celltype markers
##############################################################

DEG_dir <- "/dfs7/swaruplab/smorabit/collab/woodlab/reinstatement_2022/DEGs/celltype_markers/"
DEG_tests <- dir(DEG_dir)

combined <- Reduce(rbind, lapply(DEG_tests, function(file){
  read.csv(paste0(DEG_dir, '/', file))
}))

write.csv(
  combined,
  file='/dfs7/swaruplab/smorabit/collab/woodlab/reinstatement_2022/DEGs/data/celltype_markers.csv',
  quote=FALSE, row.names=FALSE
)

##############################################################
# celltype condition DEGs
##############################################################

DEG_dir <- "/dfs7/swaruplab/smorabit/collab/woodlab/reinstatement_2022/DEGs/celltype_Reinstatement_vs_WT/"
DEG_tests <- dir(DEG_dir)

combined <- Reduce(rbind, lapply(DEG_tests, function(file){
  read.csv(paste0(DEG_dir, '/', file))
}))

write.csv(
  combined,
  file='/dfs7/swaruplab/smorabit/collab/woodlab/reinstatement_2022/DEGs/data/celltype_Reinstatement_vs_WT_DEGs.csv',
  quote=FALSE, row.names=FALSE
)

##############################################################
# cluster condition DEGs
##############################################################

DEG_dir <- "/dfs7/swaruplab/smorabit/collab/woodlab/reinstatement_2022/DEGs/cluster_Reinstatement_vs_WT/"
DEG_tests <- dir(DEG_dir)

combined <- Reduce(rbind, lapply(DEG_tests, function(file){
  read.csv(paste0(DEG_dir, '/', file))
}))

write.csv(
  combined,
  file='/dfs7/swaruplab/smorabit/collab/woodlab/reinstatement_2022/DEGs/data/cluster_Reinstatement_vs_WT_DEGs.csv',
  quote=FALSE, row.names=FALSE
)

```

Marker gene heatmap

```{r eval=FALSE}


degs <- read.csv(file='/dfs7/swaruplab/smorabit/collab/woodlab/reinstatement_2022/DEGs/data/cluster_markers.csv')
degs$group <- factor(
  degs$group,
  levels = levels(seurat_obj$annotation)
)

n_degs <- 5
plot_genes <- degs %>%
  arrange(group) %>%
  subset(p_val_adj <= 0.05) %>%
  group_by(group) %>%
  top_n(n_degs, wt=avg_log2FC)  %>%
  .$gene

seurat_obj <- ScaleData(seurat_obj, features=plot_genes)

# set random seed
set.seed(42)

seurat_obj$barcode <- colnames(seurat_obj)
temp <- seurat_obj@meta.data %>% group_by(annotation) %>% sample_n(500)

seurat_obj$ordered_clusters <- fct_rev(seurat_obj$annotation)
p <- DoHeatmap(
  seurat_obj %>% subset(barcode %in% temp$barcode),
  features=unlist(plot_genes),
  group.by='annotation',
  raster=TRUE, slot='scale.data'
  #group.colors=cluster_colors
) +
theme(axis.text.y = element_text(face='italic', size=5))

pdf(paste0(fig_dir, 'marker_gene_heatmap.pdf'), width=16, height=8, useDingbats=FALSE)
p
dev.off()

```

Marker gene dotplot

```{r eval=FALSE}


degs <- read.csv(file='/dfs7/swaruplab/smorabit/collab/woodlab/reinstatement_2022/DEGs/data/cluster_markers.csv')
degs$group <- factor(
  degs$group,
  levels = levels(seurat_obj$annotation)
)

n_degs <- 1
plot_genes <- degs %>%
  arrange(group) %>%
  subset(p_val_adj <= 0.05) %>%
  group_by(group) %>%
  top_n(n_degs, wt=avg_log2FC)  %>%
  .$gene %>% unique()


seurat_obj$ordered_clusters <- fct_rev(seurat_obj$annotation)
p <- DotPlot(
  seurat_obj,
  features=rev(unlist(plot_genes)),
  group.by='annotation',
  dot.min = 0.05
) +
  coord_flip() + RotatedAxis() +
  scale_color_gradientn(
    colors=rev(inferno(256)),
    guide = guide_colorbar(barwidth=0.5, barheight=20, ticks=FALSE, label=FALSE)
    ) +
    ylab('') + xlab('') +
  theme(
    panel.border = element_rect(color = 'black', fill=NA, size=1),
    axis.line.y = element_blank(),
    axis.line.x = element_blank(),
    axis.text.y = element_text(face='italic')
  )
#theme(axis.text.y = element_text(face='italic', size=5))

pdf(paste0(fig_dir, 'marker_gene_dotplot.pdf'), width=10, height=7, useDingbats=FALSE)
p
dev.off()

```



Volcano Plots for DEGs:

```{r eval=FALSE}

# cluster DEGs
degs <- read.csv(file='/dfs7/swaruplab/smorabit/collab/woodlab/reinstatement_2022/DEGs/data/cluster_Reinstatement_vs_WT_DEGs.csv')
degs$group <- factor(
  degs$group,
  levels = levels(seurat_obj$annotation)
)
name <- 'cluster'

# load celltype degs:
degs <- read.csv(file='/dfs7/swaruplab/smorabit/collab/woodlab/reinstatement_2022/DEGs/data/celltype_Reinstatement_vs_WT_DEGs.csv')
degs$group <- factor(
  degs$group,
  levels = levels(seurat_obj$cell_type)
)
name <- 'celltype'

# lowest non-zero value
lowest <- degs %>% subset(p_val_adj != 0) %>% top_n(-1, wt=p_val_adj) %>% .$p_val_adj
degs$p_val_adj <- ifelse(degs$p_val_adj == 0, lowest, degs$p_val_adj)

nlabel <- 5
color1 <- 'seagreen'; color2 <- 'darkorchid3'

# label the top and bottom significant genes by log fold change
cur_degs <- Reduce(rbind, lapply(unique(degs$group), function(x){
  cur <- subset(degs, group == x)

  top_thresh <- cur %>% subset(p_val_adj <= 0.05 & avg_log2FC > 0) %>% top_n(nlabel, wt=avg_log2FC) %>% .$avg_log2FC %>% min
  bottom_thresh <- cur %>% subset(p_val_adj <= 0.05 & avg_log2FC < 0) %>% top_n(-1*nlabel, wt=avg_log2FC) %>% .$avg_log2FC %>% max

  cur$anno <- ifelse(cur$p_val_adj <= 0.05 & cur$avg_log2FC >= top_thresh, cur$gene, NA)
  cur$anno <- ifelse(cur$p_val_adj <= 0.05 & cur$avg_log2FC <= bottom_thresh, cur$gene, cur$anno)
  cur$color <- ifelse(cur$p_val_adj > 0.05, 'gray', ifelse(cur$avg_log2FC > 0, color1, color2))
  cur
}))

groups <- levels(degs$group)
plot_list <- list()
for(cluster  in groups){

  print(cluster)
  plot_degs <- cur_degs %>% subset(group == cluster)

  p <- plot_degs  %>%
     ggplot(aes(x=avg_log2FC, y=-log10(p_val_adj))) +
     geom_hline(yintercept=-log10(0.05), linetype='dashed')

  # plot genes that are Nr4a2 targets
  p <- p + ggrastr::rasterise(geom_point(
    alpha=0.5,
    color=plot_degs %>% .$color
  ), dpi=500)

  p <- p +
     geom_point(
       inherit.aes=FALSE,
       data=subset(plot_degs, !is.na(anno)),
       aes(avg_log2FC, -log10(p_val_adj)),
       fill=subset(plot_degs, !is.na(anno)) %>% .$color,
       shape=21, size=3, color='black'
     ) +
     geom_text_repel(aes(label=anno), color='black', fontface='italic',  min.segment.length=0) +
     xlim(-1*max(abs(plot_degs$avg_log2FC))-0.1, max(abs(plot_degs$avg_log2FC))+0.1) +
     ggtitle(paste0(cluster)) +
     xlab(bquote("Average log"[2]~"(Fold Change)")) +
     ylab(bquote("-log"[10]~"(Adj. P-value)")) +
     theme(
       panel.border = element_rect(color='black', fill=NA, size=1),
       panel.grid.major = element_blank(),
       axis.line = element_blank(),
       plot.title = element_text(hjust = 0.5),
       legend.position='bottom'
     )

    plot_list[[cluster]] <- p

}

out <- paste0(fig_dir, 'volcano_', name, '.pdf')

# cluster
pdf(out, width=20, height=20, useDingbats=FALSE)
wrap_plots(plot_list, ncol=5)
dev.off()

# celltype
pdf(out, width=15, height=12, useDingbats=FALSE)
wrap_plots(plot_list, ncol=4)
dev.off()


```


Violin plots for Jess:

```{r eval=FALSE}

library(hdWGCNA)

# re-load the Nurr2c dataset

seurat_nurr2c <- readRDS('/dfs7/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/data/harmony_annotated_scWGCNA.rds')

target_genes <- GetMotifTargets(seurat_nurr2c)
nr4a2_targets <- target_genes$NR4A2
head(nr4a2_targets)

# sanity check the group labels by plotting the top DEGs

plot_genes <- subset(degs, group == 'MHb') %>% slice_max(avg_log2FC, n=5) %>% .$gene


plot_list <- list()
for(gene in plot_genes){
  plot_list[[gene]] <- VlnPlot(seurat_obj, group.by = 'cell_type', split.by='Group', feature=gene, pt.size=0) + xlab('')
}


pdf(paste0(fig_dir, "test_vln.pdf"), width=8, height=10, useDingbats=FALSE)
wrap_plots(plot_list, ncol=1) + plot_layout(guides='collect')
dev.off()

################################################################################
#
################################################################################

library(ggpubr)

plot_genes <- c(
  'Nr4a2',
  'Gabarap', 'Gabbr1', 'Gabbr2', 'Gabrd', 'Gabarapl1',
  'Atp5k', 'Uqcr11', 'Atp5j2', 'Ndufb5', 'Cox5b', 'Fis1', 'Tomm5'
)

p <- custom_vln(
    seurat_obj,
    features = plot_genes,
    group.by = 'annotation',
    groups = c('MHb1', 'MHb2', 'MHb3', 'MHb4', 'MHb5'),
    add_boxplot=FALSE,
    split.by = 'Group',
    split_colors=c('seagreen', 'darkorchid3'),
    add_colorbar=FALSE,
    plot_ymin = 0
    #add.noise=TRUE
  )


pdf(paste0(fig_dir, 'selected_DEGs_stacked_vln.pdf'), width=5, height=8)
p
dev.off()


p <- custom_vln(
    seurat_obj,
    features = plot_genes,
    group.by = 'cell_type',
    groups = c('MHb'),
    add_boxplot=FALSE,
    split.by = 'Group',
    split_colors=c('seagreen', 'darkorchid3'),
    add_colorbar=FALSE,
    plot_ymin = 0
    #add.noise=TRUE
  )


pdf(paste0(fig_dir, 'selected_DEGs_stacked_vln_celltype.pdf'), width=3, height=8)
p
dev.off()



```
