```{r eval=FALSE}

# conda activate cicero

library(Seurat)
library(tidyverse)
library(RColorBrewer)
library(MetBrewer)
library(viridis)
library(patchwork)
library(cowplot)
library(grid)
library(gridExtra)
library(WGCNA)
library(hdWGCNA)
theme_set(theme_cowplot())

source('/dfs7/swaruplab/smorabit/pipelines/sn-rna-seq/bin/sc_utilities.R')


setwd('/dfs7/swaruplab/smorabit/collab/woodlab/reinstatement_2022')

# output directories
data_dir <- "data/"
fig_dir <- 'figures/'

# load seurat obj
seurat_obj <- readRDS("/dfs7/swaruplab/smorabit/collab/woodlab/reinstatement_2022/data/Reinstatement_2022_seurat.rds")


```


UMAP plots

```{r eval=FALSE}

library(hdWGCNA)

###########################################################
# color by cell type
###########################################################

p <- PlotEmbedding(
  seurat_obj,
  group.by = 'cell_type',
  label=TRUE,
  raster=TRUE,
  raster_dpi = 200,
  point_size = 0.5,
  raster_scale = 0.25,
  plot_theme = umap_theme() + NoLegend()
)

pdf(paste0(fig_dir, 'umap_celltype.pdf'),  width=6, height=6, useDingbats=FALSE)
p
dev.off()

###########################################################
# color by sample
###########################################################

p <- PlotEmbedding(
  seurat_obj,
  group.by = 'Sample',
  label=FALSE,
  raster=TRUE,
  raster_dpi = 200,
  point_size = 0.5,
  raster_scale = 0.25,
  plot_theme = umap_theme() + NoLegend()
)

pdf(paste0(fig_dir, 'umap_Sample.pdf'),  width=6, height=6, useDingbats=FALSE)
p
dev.off()

###########################################################
# color by Batch
###########################################################

p <- PlotEmbedding(
  seurat_obj,
  group.by = 'Assignment',
  label=FALSE,
  raster=TRUE,
  raster_dpi = 200,
  point_size = 0.5,
  raster_scale = 0.25,
  plot_theme = umap_theme() + NoLegend()
)

pdf(paste0(fig_dir, 'umap_Batch.pdf'),  width=6, height=6, useDingbats=FALSE)
p
dev.off()

###########################################################
# color by Sample split by Batch
###########################################################

plot_list <- PlotEmbedding(
  seurat_obj,
  group.by = 'Sample',
  split.by = 'Assignment',
  label=FALSE,
  raster=TRUE,
  raster_dpi = 200,
  point_size = 0.5,
  raster_scale = 0.25,
  plot_theme = umap_theme() + NoLegend()
)

pdf(paste0(fig_dir, 'umap_Sample_splitby_Batch.pdf'),  width=12, height=4, useDingbats=FALSE)
wrap_plots(plot_list, ncol=3)
dev.off()


###########################################################
# color by cell type split by condition
###########################################################

plot_list <- PlotEmbedding(
  seurat_obj,
  group.by = 'cell_type',
  split.by = 'Group',
  plot_under=TRUE,
  label=TRUE,
  raster=TRUE,
  raster_dpi = 200,
  point_size = 0.5,
  raster_scale = 0.25,
  plot_theme = umap_theme() + NoLegend()
)

pdf(paste0(fig_dir, 'umap_celltype_split_condition.pdf'),  width=8, height=4, useDingbats=FALSE)
wrap_plots(plot_list, ncol=2)
dev.off()


###########################################################
# color by annotation split by batch
###########################################################

p <- PlotEmbedding(
  seurat_obj,
  group.by = 'annotation',
  label=TRUE,
  raster=TRUE,
  raster_dpi = 200,
  point_size = 0.5,
  raster_scale = 0.25,
  plot_theme = umap_theme() + NoLegend()
)

pdf(paste0(fig_dir, 'umap_annotation.pdf'),  width=6, height=6, useDingbats=FALSE)
p
dev.off()

###########################################################
# color by annotation split by batch
###########################################################

plot_list <- PlotEmbedding(
  seurat_obj,
  group.by = 'annotation',
  split.by = 'Assignment',
  plot_under=TRUE,
  label=TRUE,
  raster=TRUE,
  raster_dpi = 200,
  point_size = 0.5,
  raster_scale = 0.25,
  plot_theme = umap_theme() + NoLegend()
)

pdf(paste0(fig_dir, 'umap_annotation_split_Batch.pdf'),  width=12, height=4, useDingbats=FALSE)
wrap_plots(plot_list, ncol=3)
dev.off()

```

Stacked bar plot

```{r eval=FALSE}

###########################################################
# Proportion of batch in each cluster
###########################################################

seurat_meta <- seurat_obj@meta.data
batches <- seurat_meta$Assignment %>% unique %>% as.character
cur_clusters  <- seurat_meta$annotation %>% unique %>% as.character

scale_vec <- table(seurat_meta$Assignment)

proportion_df <- data.frame()
for(i in 1:length(cur_clusters)){
  cluster_meta <- subset(seurat_meta, annotation == cur_clusters[i])
  cur_df <- as.data.frame(table(cluster_meta$Assignment)) %>% dplyr::rename(Count = Freq)

  # compute the non-normalized % of cells in each group
  cur_df$Freq <- cur_df$Count / sum(cur_df$Count)

  # scale frequency to the total number of clusters in each sample
  cur_df$Scaled <- cur_df$Count / scale_vec
  cur_df$Scaled <- cur_df$Scaled / sum(cur_df$Scaled)

  # add to ongoing proportion df
  cur_df$cluster <- cur_clusters[i]
  proportion_df <- rbind(proportion_df, cur_df)
}

proportion_df <- dplyr::rename(proportion_df, Assignment = Var1)
proportion_df$cluster <- factor(proportion_df$cluster, levels=levels(seurat_meta$annotation))

p <- ggplot(proportion_df, aes(y=Scaled, x=cluster, fill=Assignment)) +
  geom_bar(stat='identity') +
  scale_y_continuous(expand = c(0,0)) +
  #scale_fill_manual(values=c('gray65', 'gray45')) +
  theme(
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    axis.text.x = element_text(angle=45, hjust=1),
    axis.title.x = element_blank(),
    legend.title = element_blank(),
    axis.line.y = element_line(colour = "black"),
    axis.line.x = element_blank()
  )

pdf(paste0(fig_dir, 'cluster_proportion_batch_scaled.pdf'), height=4, width=10)
print(p)
dev.off()

p <- ggplot(proportion_df, aes(y=Freq, x=cluster, fill=Assignment)) +
  geom_bar(stat='identity') +
  scale_y_continuous(expand = c(0,0)) +
  #scale_fill_manual(values=c('gray65', 'gray45')) +
  theme(
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    axis.text.x = element_text(angle=45, hjust=1),
    axis.title.x = element_blank(),
    legend.title = element_blank(),
    axis.line.y = element_line(colour = "black"),
    axis.line.x = element_blank()
  )

pdf(paste0(fig_dir, 'cluster_proportion_batch_raw.pdf'), height=4, width=10)
print(p)
dev.off()


###########################################################
# Proportion of Samplex in each cluster
###########################################################

seurat_obj$Sample <- as.factor(seurat_obj$Sample)

seurat_meta <- seurat_obj@meta.data
batches <- seurat_meta$Sample %>% unique %>% as.character
cur_clusters  <- seurat_meta$annotation %>% unique %>% as.character

scale_vec <- table(seurat_meta$Sample)

proportion_df <- data.frame()
for(i in 1:length(cur_clusters)){
  cluster_meta <- subset(seurat_meta, annotation == cur_clusters[i])
  cur_df <- as.data.frame(table(cluster_meta$Sample)) %>% dplyr::rename(Count = Freq)

  # compute the non-normalized % of cells in each group
  cur_df$Freq <- cur_df$Count / sum(cur_df$Count)

  # scale frequency to the total number of clusters in each sample
  cur_df$Scaled <- cur_df$Count / scale_vec
  cur_df$Scaled <- cur_df$Scaled / sum(cur_df$Scaled)

  # add to ongoing proportion df
  cur_df$cluster <- cur_clusters[i]
  proportion_df <- rbind(proportion_df, cur_df)
}

proportion_df <- dplyr::rename(proportion_df, Sample = Var1)
proportion_df$cluster <- factor(proportion_df$cluster, levels=levels(seurat_meta$annotation))

p <- ggplot(proportion_df, aes(y=Scaled, x=cluster, fill=Sample)) +
  geom_bar(stat='identity') +
  scale_y_continuous(expand = c(0,0)) +
  #scale_fill_manual(values=c('gray65', 'gray45')) +
  theme(
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    axis.text.x = element_text(angle=45, hjust=1),
    axis.title.x = element_blank(),
    legend.title = element_blank(),
    axis.line.y = element_line(colour = "black"),
    axis.line.x = element_blank()
  )

pdf(paste0(fig_dir, 'cluster_proportion_sample_scaled.pdf'), height=4, width=10)
print(p)
dev.off()

p <- ggplot(proportion_df, aes(y=Freq, x=cluster, fill=Sample)) +
  geom_bar(stat='identity') +
  scale_y_continuous(expand = c(0,0)) +
  #scale_fill_manual(values=c('gray65', 'gray45')) +
  theme(
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    axis.text.x = element_text(angle=45, hjust=1),
    axis.title.x = element_blank(),
    legend.title = element_blank(),
    axis.line.y = element_line(colour = "black"),
    axis.line.x = element_blank()
  )

pdf(paste0(fig_dir, 'cluster_proportion_Sample_raw.pdf'), height=4, width=10)
print(p)
dev.off()


```


QC Violin plots

```{r eval=FALSE}


################################################################################
# Cluster level violin plots:
################################################################################

Idents(seurat_obj) <- seurat_obj$annotation
p <- VlnPlot(seurat_obj, features = 'total_counts', pt.size=0) +
  geom_boxplot(outlier.shape=NA, width=.25, fill='white') +
  #scale_fill_manual(values=cluster_colors) +
  scale_y_continuous(labels=scales::comma) +
  ylab(expression(italic(N)[UMI])) +
  xlab('') + NoLegend() + ggtitle('')

pdf(paste0(fig_dir, 'vln_nUMI_clusters.pdf'), height=4, width=10)
p
dev.off()


p <- VlnPlot(seurat_obj, features = 'pct_counts_mt', pt.size=0) +
  geom_boxplot(outlier.shape=NA, width=.25, fill='white') +
  #scale_fill_manual(values=cluster_colors) +
  scale_y_continuous(labels=scales::comma) +
  ylab("pct_counts_mt") +
  xlab('') + NoLegend() + ggtitle('')

pdf(paste0(fig_dir, 'vln_mito_clusters.pdf'), height=4, width=10)
p
dev.off()

p <- VlnPlot(seurat_obj, features = 'n_genes_by_counts', pt.size=0) +
  geom_boxplot(outlier.shape=NA, width=.25, fill='white') +
#  scale_fill_manual(values=cluster_colors) +
  scale_y_continuous(labels=scales::comma) +
  ylab(expression(italic(N)[Genes])) +
  xlab('') + NoLegend() + ggtitle('')

pdf(paste0(fig_dir, 'vln_nGenes_clusters.pdf'), height=4, width=10)
p
dev.off()


################################################################################
# Sample level violin plots:
################################################################################

Idents(seurat_obj) <- seurat_obj$Sample
p <- VlnPlot(seurat_obj, features = 'total_counts', pt.size=0) +
  geom_boxplot(outlier.shape=NA, width=.25, fill='white') +
  scale_y_continuous(labels=scales::comma) +
  ylab(expression(italic(N)[UMI])) +
  xlab('') + NoLegend() + ggtitle('')

pdf(paste0(fig_dir, 'vln_nUMI_samples.pdf'), height=4, width=10)
p
dev.off()


p <- VlnPlot(seurat_obj, features = 'pct_counts_mt', pt.size=0) +
  geom_boxplot(outlier.shape=NA, width=.25, fill='white') +
  scale_y_continuous(labels=scales::comma) +
  ylab("pct_counts_mt") +
  xlab('') + NoLegend() + ggtitle('')

pdf(paste0(fig_dir, 'vln_mito_samples.pdf'), height=4, width=10)
p
dev.off()

p <- VlnPlot(seurat_obj, features = 'n_genes_by_counts', pt.size=0) +
  geom_boxplot(outlier.shape=NA, width=.25, fill='white') +
  scale_y_continuous(labels=scales::comma) +
  ylab(expression(italic(N)[Genes])) +
  xlab('') + NoLegend() + ggtitle('')

pdf(paste0(fig_dir, 'vln_nGenes_samples.pdf'), height=4, width=10)
p
dev.off()

```


Ex vivo activation signature

```{r eval=FALSE}

exam_genes <- read.csv('~/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/Nurr2c_vs_GFP/data/exAMgenes_Marsh2022.csv')

genes_test <- exam_genes$ExAm_ALL
genes_test <- genes_test[genes_test != '']
genes_test <- genes_test[genes_test %in% rownames(seurat_obj)]

# compute the exam score
exam_score <-  Seurat::AddModuleScore(seurat_obj, features=list('exam' = genes_test))@meta.data
exam_score <- exam_score[,ncol(exam_score)]

# add score to seurat object
seurat_obj$exam_score <- exam_score

# compute the exam score
exam_score <- UCell::AddModuleScore_UCell(seurat_obj, features=list('exam' = genes_test))@meta.data
exam_score <- exam_score[,ncol(exam_score)]



# add score to seurat object
seurat_obj$exam_score_ucell <- exam_score



p <- FeatureEmbedding(
  seurat_obj,
  features=c('exam_score', 'exam_score_ucell'),
  plot_max=NULL,
  plot_min=0,
  ncol=2,
  dpi=200,
  point_size=0.25,
  dpi_scale=0.25,
  order_points='shuffle'
)


p <- FeatureEmbedding(
  seurat_obj,
  features=c('exam_score_ucell'),
  plot_max=1,
  plot_min=0,
  ncol=2,
  dpi=500,
  point_size=0.25,
  dpi_scale=0.25,
  order_points='shuffle'
)




pdf(paste0(fig_dir, 'umap_exam_score.pdf'), width=5, height=5)
p
dev.off()


p <- FeatureEmbedding(
  seurat_obj,
  features=c('doublet_scores'),
  plot_max=1,
  plot_min=0.05,
  ncol=2,
  dpi=500,
  point_size=0.25,
  dpi_scale=0.25,
  order_points='shuffle'
)

pdf(paste0(fig_dir, 'umap_doublet_score.pdf'), width=5, height=5)
p
dev.off()


```


Barplot showing umber of cells in each cell-type

```{r eval=FALSE}



df <- as.data.frame(table((seurat_obj@meta.data$cell_type)))
df$Var1 <- fct_rev(df$Var1)

p <- ggplot(df, aes(x=reorder(Var1, Freq), y=Freq, fill=Var1, )) +
  geom_bar(stat='identity') +
  geom_text(aes(label=scales::comma(Freq)),  color="black", size=3.5, hjust='inward') +
  scale_y_continuous(labels=scales::comma) +
  #scale_fill_manual(values=celltype_colors) +
  coord_flip() + NoLegend() + RotatedAxis() + xlab('') + ylab('') +
  #scale_fill_manual(values=celltype_colors) +
  theme(
    plot.title = element_text(hjust = 0.5),
    panel.grid.minor=element_blank(),
    panel.grid.major=element_blank(),
    axis.ticks.y=element_blank(),
    axis.ticks.x=element_blank(),
    axis.title.x=element_blank(),
    axis.line=element_blank(),
    axis.text.x = element_blank()
  )


pdf(paste0(fig_dir, 'barplot_nCells_celltypes.pdf'), width=3, height=3)
p
dev.off()


tmp <- subset(seurat_obj@meta.data, Group == 'Reinstatement')
df <- as.data.frame(table((tmp$cell_type)))
df$Var1 <- fct_rev(df$Var1)

p1 <- ggplot(df, aes(x=reorder(Var1, Freq), y=Freq, fill=Var1, )) +
  geom_bar(stat='identity') +
  geom_text(aes(label=scales::comma(Freq)),  color="black", size=3.5, hjust='inward') +
  scale_y_continuous(labels=scales::comma) +
  #scale_fill_manual(values=celltype_colors) +
  coord_flip() + NoLegend() + RotatedAxis() + xlab('') + ylab('') +
  # scale_fill_manual(values=celltype_colors) +
  theme(
    plot.title = element_text(hjust = 0.5),
    panel.grid.minor=element_blank(),
    panel.grid.major=element_blank(),
    axis.ticks.y=element_blank(),
    axis.ticks.x=element_blank(),
    axis.title.x=element_blank(),
    axis.line=element_blank(),
    axis.text.x = element_blank()
  ) + ggtitle('Reinstatement')



tmp <- subset(seurat_obj@meta.data, Group == 'NR')
df <- as.data.frame(table((tmp$cell_type)))
df$Var1 <- fct_rev(df$Var1)

p2 <- ggplot(df, aes(x=reorder(Var1, Freq), y=Freq, fill=Var1, )) +
  geom_bar(stat='identity') +
  geom_text(aes(label=scales::comma(Freq)),  color="black", size=3.5, hjust='inward') +
  scale_y_continuous(labels=scales::comma) +
  #scale_fill_manual(values=celltype_colors) +
  coord_flip() + NoLegend() + RotatedAxis() + xlab('') + ylab('') +
  # scale_fill_manual(values=celltype_colors) +
  theme(
    plot.title = element_text(hjust = 0.5),
    panel.grid.minor=element_blank(),
    panel.grid.major=element_blank(),
    axis.ticks.y=element_blank(),
    axis.ticks.x=element_blank(),
    axis.title.x=element_blank(),
    axis.line=element_blank(),
    axis.text.x = element_blank()
  ) + ggtitle('NR')


pdf(paste0(fig_dir, 'barplot_nCells_celltypes_split_condition.pdf'), width=6, height=3)
p1 + p2
dev.off()


```
