#!/bin/bash
#SBATCH --job-name=ct_FindMarkers
#SBATCH -p standard
#SBATCH -A vswarup_lab
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --error=slurm-%J.err
#SBATCH --mem 48G
#SBATCH --array=1-10
#SBATCH --time=5:00:00

source ~/.bashrc
conda activate cicero

# seurat object path:
seurat="/dfs7/swaruplab/smorabit/collab/woodlab/reinstatement_2022/data/Reinstatement_2022_seurat.rds"
outdir="/dfs7/swaruplab/smorabit/collab/woodlab/reinstatement_2022/DEGs/celltype_markers/"
type="markers"
name="celltype"
cluster="cell_type"
latent="total_counts,Assignment"

# launch R script:
Rscript --vanilla ~/swaruplab/smorabit/collab/woodlab/cocaine_mouse_2021/bin/parallel_DEGs.R \
    --seurat $seurat \
    --outdir $outdir \
    --type $type \
    --cluster $cluster \
    --name $name \
    --index $SLURM_ARRAY_TASK_ID \
    --test "MAST" \
    --pos "FALSE" \
    --pct 0.1 \
    --logfc 0.1 \
    --verbose "TRUE" \
    --latent $latent \
    --cores 16
